name: Lint with mypy

on: push

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.12
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install requirements
        run: |
            pip install --upgrade pip
            pip install poetry
            poetry install --with dev
            poetry run pip freeze > requirements.txt
            pip install -r requirements.txt
            pip install .
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
