name: Request

on: 
    schedule:
    - cron: "*/14 8-23 * * *"

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request
        uses: satak/webrequest-action@master
        with:
            url: https://mstudents.onrender.com/
            method: GET
      - name: Request
        uses: satak/webrequest-action@master
        with:
            url: https://pmanager-server.onrender.com/
            method: GET
