name: Request

on: 
    push:
    schedule:
    - cron: "*/5 * * * *"

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request
        uses: satak/webrequest-action@master
        with:
            url: https://mstudents.onrender.com/
            method: GET